# Generated by Django 5.2.3 on 2025-06-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('AUSTRALIA', 'Austrália'), ('BRAZIL', 'Brasil'), ('CANADA', 'Canadá'), ('CHINA', 'China'), ('FRANCE', 'França'), ('GERMANY', 'Alemanha'), ('INDIA', 'Índia'), ('ITALY', 'Itália'), ('UK', 'Reino Unido'), ('USA', 'Estados Unidos'), ('OTHER', 'Outro')], max_length=50, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['name'],
            },
        ),
    ]
